SELECT * FROM AUDITORIUM_TYPE FULL OUTER JOIN AUDITORIUM
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM is NULL


SELECT * FROM AUDITORIUM FULL OUTER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM is NULL


SELECT * FROM AUDITORIUM FULL OUTER JOIN AUDITORIUM_TYPE
ON AUDITORIUM.AUDITORIUM_TYPE = AUDITORIUM_TYPE.AUDITORIUM_TYPE
WHERE AUDITORIUM.AUDITORIUM_TYPE is not NULL and AUDITORIUM_TYPE.AUDITORIUM_TYPE is not NULL
