use UNIVER;

SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY ROLLUP (FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT);



SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY CUBE (FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT);





SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
UNION
SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ТОВ'
GROUP BY  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT;


SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
UNION ALL
SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ТОВ'
GROUP BY  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT;



SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
INTERSECT
SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ТОВ'
GROUP BY  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT;





SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ТОВ'
GROUP BY  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT
EXCEPT
SELECT FACULTY.FACULTY,  GROUPS.PROFESSION, PROGRESS.SUBJECT, round(avg(cast(PROGRESS.NOTE as float(1))),2) as [средняя оценка]
FROM  FACULTY 
			  inner join GROUPS on GROUPS.FACULTY = FACULTY.FACULTY
			  inner join STUDENT on STUDENT.IDGROUP = GROUPS.IDGROUP
			  inner join PROGRESS on PROGRESS.IDSTUDENT = STUDENT.IDSTUDENT

WHERE FACULTY.FACULTY like 'ХТиТ'
GROUP BY  FACULTY.FACULTY, GROUPS.PROFESSION, PROGRESS.SUBJECT;


