use UNIVER;

SELECT distinct PULPIT.PULPIT_NAME
FROM FACULTY, PULPIT, PROFESSION
WHERE PULPIT.FACULTY=FACULTY.FACULTY
AND FACULTY.FACULTY In (Select PROFESSION.FACULTY FROM PROFESSION 
					WHERE PROFESSION_NAME Like '%технологии%'
					or PROFESSION_NAME Like '%технология%')



SELECT distinct PULPIT.PULPIT_NAME
FROM FACULTY inner join PULPIT 
on FACULTY.FACULTY=PULPIT.FACULTY
WHERE FACULTY.FACULTY In (Select PROFESSION.FACULTY FROM PROFESSION 
					WHERE PROFESSION_NAME Like '%технологии%'
					or PROFESSION_NAME Like '%технология%')

SELECT distinct PULPIT.PULPIT_NAME
FROM FACULTY inner join PULPIT 
on FACULTY.FACULTY=PULPIT.FACULTY
inner join PROFESSION
			ON PROFESSION.FACULTY = FACULTY.FACULTY
			WHERE PROFESSION_NAME Like '%технологии%'
					or PROFESSION_NAME Like '%технология%'


SELECT AUDITORIUM_NAME, AUDITORIUM_TYPE, AUDITORIUM_CAPACITY
FROM AUDITORIUM a1
where AUDITORIUM_CAPACITY = (select top(1) AUDITORIUM_CAPACITY from AUDITORIUM a2
		where a2.AUDITORIUM_TYPE = a1.AUDITORIUM_TYPE
									order by AUDITORIUM_CAPACITY desc)
order by AUDITORIUM_CAPACITY desc;



SELECT FACULTY.FACULTY_NAME from FACULTY
WHERE not exists (select* from PULPIT
			WHERE PULPIT.FACULTY = FACULTY.FACULTY)


SELECT top 1
	(select avg(NOTE) from PROGRESS
			where PROGRESS.SUBJECT like 'ОАиП') [ОАиП],
	(select avg(NOTE) from PROGRESS
			where PROGRESS.SUBJECT like 'БД') [КГ],
	(select avg(NOTE) from PROGRESS
			where PROGRESS.SUBJECT like 'СУБД') [СУБД]
FROM PROGRESS


SELECT NOTE, SUBJECT 
FROM PROGRESS	
	where NOTE>= all(select NOTE from PROGRESS WHERE SUBJECT like 'ОАиП')


SELECT NOTE, SUBJECT 
FROM PROGRESS	
	where NOTE>= any(select NOTE from PROGRESS WHERE SUBJECT like 'ОАиП')

